# Generated by Django 3.0.5 on 2020-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='year2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package', models.CharField(max_length=200)),
                ('CSE', models.IntegerField(default=0)),
                ('ECE', models.IntegerField(default=0)),
                ('EEE', models.IntegerField(default=0)),
                ('IT', models.IntegerField(default=0)),
                ('MECH', models.IntegerField(default=0)),
                ('CIVIL', models.IntegerField(default=0)),
                ('MCA', models.IntegerField(default=0)),
                ('MEECE', models.IntegerField(default=0)),
                ('MEMech', models.IntegerField(default=0)),
                ('MECOMM', models.IntegerField(default=0)),
                ('MECSE', models.IntegerField(default=0)),
                ('MEEEE', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
    ]
